# Generated by Django 4.2.3 on 2023-07-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu_items',
            old_name='spice_level',
            new_name='spicy_level',
        ),
    ]
