# Generated by Django 4.2.3 on 2023-07-28 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20230728_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu_items',
            old_name='cuisine',
            new_name='cuisine_type',
        ),
    ]
